development:
  MAILCHIMP_API_KEY: a7b7cff7ba85150aba40bf15fc470e07-us17
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  MAILCHIMP_API_KEY: a7b7cff7ba85150aba40bf15fc470e07-us17

